apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: booli-targets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: dGFyZ2V0cw==
  MYSQL_USER: dGFyZ2V0cw==
  MYSQL_PASSWORD: cGFzc3dvcmQ=