apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booli-targets
  namespace: booli-targets
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: target.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: booli-targets
            port:
              number: 8080
